export type KuwaitArea = { en: string; ar: string };

// Source: Common Kuwait areas (based on public listings, e.g. "Areas of Kuwait").
// Note: If an area is missing, the checkout field still allows manual typing.
export const KUWAIT_AREAS: KuwaitArea[] = [
  // Capital (Al Asimah)
  { en: "Abdullah Al-Salem", ar: "عبد الله السالم" },
  { en: "Adailiya", ar: "العديلية" },
  { en: "Al-Sour Gardens", ar: "حدائق السور" },
  { en: "Bneid Al-Gar", ar: "بنيد القار" },
  { en: "Daiya", ar: "الدعية" },
  { en: "Dasma", ar: "الدسمة" },
  { en: "Doha", ar: "الدوحة" },
  { en: "Doha Port", ar: "ميناء الدوحة" },
  { en: "Faiha", ar: "الفيحاء" },
  { en: "Failaka Island", ar: "فيلكا" },
  { en: "Granada", ar: "غرناطة" },
  { en: "Jibla", ar: "جِبْلَة" },
  { en: "Kaifan", ar: "كيفان" },
  { en: "Khaldiya", ar: "الخالدية" },
  { en: "Mansouriya", ar: "المنصورية" },
  { en: "Mirqab", ar: "المرقاب" },
  { en: "Nahdha", ar: "النهضة" },
  { en: "North West Sulaibikhat", ar: "شمال غرب الصليبيخات" },
  { en: "Nuzha", ar: "النزهة" },
  { en: "Qadsiya", ar: "القادسية" },
  { en: "Qortuba", ar: "قرطبة" },
  { en: "Rawda", ar: "الروضة" },
  { en: "Shamiya", ar: "الشامية" },
  { en: "Sharq", ar: "شرق" },
  { en: "Shuwaikh", ar: "الشويخ" },
  { en: "Shuwaikh Industrial", ar: "الشويخ الصناعية" },
  { en: "Shuwaikh Port", ar: "ميناء الشويخ" },
  { en: "Sulaibikhat", ar: "الصليبخات" },
  { en: "Qairawan", ar: "القيروان" },
  { en: "Surra", ar: "السرة" },
  { en: "Umm an Namil Island", ar: "جزيرة ام النمل" },
  { en: "Yarmouk", ar: "اليرموك" },

  // Hawalli
  { en: "Bayan", ar: "بيان" },
  { en: "Jabriya", ar: "الجابرية" },
  { en: "Rumaithiya", ar: "الرميثية" },
  { en: "Salam", ar: "سلام" },
  { en: "Salwa", ar: "سلوى" },
  { en: "Al-Bida'a", ar: "البدع" },
  { en: "Hawalli", ar: "حولي" },
  { en: "Hittin", ar: "حطين" },
  { en: "Mishref", ar: "مشرف" },
  { en: "Mubarak Al-Abdullah", ar: "مبارك العبدالله" },
  { en: "Salmiya", ar: "السالمية" },
  { en: "Shaab", ar: "الشعب" },
  { en: "Shuhada", ar: "الشهداء" },
  { en: "Al-Siddiq", ar: "الصديق" },
  { en: "Ministries Area", ar: "منطقة الوزارات" },
  { en: "Zahra", ar: "الزهراء" },

  // Mubarak Al-Kabeer
  { en: "Abu Al Hasaniya", ar: "أبو الحصانية" },
  { en: "Abu Ftaira", ar: "أبو فطيرة" },
  { en: "Al-Adan", ar: "العدان" },
  { en: "Al-Qurain", ar: "القرين" },
  { en: "Al-Qusour", ar: "القصور" },
  { en: "Al-Fnaitees", ar: "الفنيطيس" },
  { en: "Messila", ar: "المسيلة" },
  { en: "Al-Masayel", ar: "المسايل" },
  { en: "Mubarak Al-Kabeer", ar: "مبارك الكبير" },
  { en: "Sabah Al-Salem", ar: "صباح السالم" },
  { en: "Subhan", ar: "صبحان" },
  { en: "West Abu Ftaira Herafiya", ar: "غرب ابو فطيرة حرفية" },

  // Ahmadi
  { en: "Abu Halifa", ar: "أبو حليفة" },
  { en: "Mina Abdullah", ar: "ميناء عبد الله" },
  { en: "Ahmadi", ar: "الأحمدي" },
  { en: "Ali Sabah Al-Salem", ar: "علي صباح السالم" },
  { en: "Egaila", ar: "العقيلة" },
  { en: "Dhaher", ar: "الظهر" },
  { en: "Fahaheel", ar: "الفحيحيل" },
  { en: "Fahad Al-Ahmad", ar: "فهد الأحمد" },
  { en: "Hadiya", ar: "هدية" },
  { en: "Jaber Al-Ali", ar: "جابر العلي" },
  { en: "Khiran", ar: "الخيران" },
  { en: "Mahboula", ar: "المهبولة" },
  { en: "Mangaf", ar: "المنقف" },
  { en: "Wafra Residential", ar: "وفرة السكنية" },
  { en: "Nuwaiseeb", ar: "النويصيب" },
  { en: "Riqqa", ar: "الرقة" },
  { en: "Sabah Al Ahmad", ar: "صباح الأحمد" },
  { en: "Sabah Al Ahmad Sea City", ar: "مدينة صباح الأحمد البحرية" },
  { en: "Sabahiya", ar: "الصباحية" },
  { en: "South Sabahiya", ar: "جنوب الصباحية" },
  { en: "Wafra", ar: "الوفرة" },
  { en: "Zoor", ar: "الزور" },
  { en: "Fintas", ar: "الفنطاس" },
  { en: "Umm Al Hayman", ar: "أم الهيمان" },

  // Farwaniya
  { en: "Abdullah Al-Mubarak", ar: "عبدالله المبارك" },
  { en: "Airport District", ar: "منطقة المطار" },
  { en: "Andalus", ar: "الأندلس" },
  { en: "Ardiya", ar: "العارضية" },
  { en: "Ardiya Herafiya", ar: "العارضية حرفية" },
  { en: "Ishbiliya", ar: "اشبيلية" },
  { en: "Al-Dajeej", ar: "الضجيج" },
  { en: "Farwaniya", ar: "الفروانية" },
  { en: "Ferdous", ar: "الفردوس" },
  { en: "Jleeb Al-Shuyoukh", ar: "جليب الشيوخ" },
  { en: "Khaitan", ar: "خيطان" },
  { en: "Omariya", ar: "العمرية" },
  { en: "Rabiya", ar: "الرابية" },
  { en: "Al-Rai", ar: "الري" },
  { en: "Al-Riggai", ar: "الرقعي" },
  { en: "Rehab", ar: "الرحاب" },
  { en: "Sabah Al-Nasser", ar: "صباح الناصر" },

  // Jahra
  { en: "Abdali", ar: "العبدلي" },
  { en: "Al-Mutlaa", ar: "المطلاع" },
  { en: "Kazma", ar: "كازما" },
  { en: "Bahra", ar: "بحرة" },
  { en: "Kabd", ar: "كبد" },
  { en: "Al-Sheqaya", ar: "الشقايه" },
  { en: "Al-Nahda", ar: "النهضة" },
  { en: "Amghara", ar: "أمغرة" },
  { en: "Jahra", ar: "الجهراء" },
  { en: "Naeem", ar: "النعيم" },
  { en: "Nasseem", ar: "النسيم" },
  { en: "Oyoun", ar: "العيون" },
  { en: "Qasr", ar: "القصر" },
  { en: "Jaber Al-Ahmad", ar: "جابر الأحمد" },
  { en: "Saad Al Abdullah", ar: "سعد العبدالله" },
  { en: "Salmi", ar: "السالمي" },
  { en: "Subiya", ar: "الصبية" },
  { en: "Sulaibiya", ar: "الصليبية" },
  { en: "Taima", ar: "تيماء" },
  { en: "Waha", ar: "الواحة" },
];

